
INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'La buena vida / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_buenavida.jpg" />\r\n</div>\r\n</div>\r\n<p> La buena vida / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist_labuenavida.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fla-buena-vida-sergio-mancera%2F" frameborder="0" ></iframe>', '2017-7-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Pa' Bailar sentado / by K.S.M /', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_CCXXVIII.jpg" />\r\n</div>\r\n</div>\r\n<p> Pa\' Bailar sentado / by K.S.M / </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/CCXXVIII.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fpa-bailar-sentado%2F" frameborder="0" ></iframe>', '2017-7-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Días salados / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_saladogrande.gif" />\r\n</div>\r\n</div>\r\n<p> Días salados / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist_salado.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fd%C3%ADas-salados%2F" frameborder="0" ></iframe>', '2017-7-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Low ways III / by K.S.M / Drawing by: Doina Kraal', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_CCXXVIIdoi2.jpg" />\r\n</div>\r\n</div>\r\n<p> Low ways III / by K.S.M / Drawing by: Doina Kraal </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/CCXXVII.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Flow-ways-iii%2F" frameborder="0" ></iframe>', '2017-7-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Dicen / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_dicen.jpg" />\r\n</div>\r\n</div>\r\n<p> Dicen / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist_dicen.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fdicen%2F" frameborder="0" ></iframe>', '2017-7-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Aves / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_CCXXV_KS.jpg" />\r\n</div>\r\n</div>\r\n<p> Aves / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/CCXXV_KS.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Faves-kevin-sim%C3%B3n-mancera%2F" frameborder="0" ></iframe>', '2017-8-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Denim & Leather / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_Kevin mancera X225.jpg" />\r\n</div>\r\n</div>\r\n<p> Denim & Leather / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/Denim%20&%20Leather.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fdenim-leather%2F" frameborder="0" ></iframe>', '2017-8-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Bandera / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_bandera.png" />\r\n</div>\r\n</div>\r\n<p> Bandera / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlistbandera.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fbandera-sergio-mancera%2F" frameborder="0" ></iframe>', '2017-8-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Perdido / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_224_K_S_perdido.jpg" />\r\n</div>\r\n</div>\r\n<p> Perdido / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/224_k_s_perdido_PL.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fperdido%2F" frameborder="0" ></iframe>', '2017-8-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Televida / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_sergio tv 3.jpg" />\r\n</div>\r\n</div>\r\n<p> Televida / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlisttele.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Ftelevida%2F" frameborder="0" ></iframe>', '2017-8-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Ultimo servicio / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/12_ultimo.gif" />\r\n</div>\r\n</div>\r\n<p> Ultimo servicio / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlistultimo.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2F%C3%BAltimo-servicio%2F" frameborder="0" ></iframe>', '2017-9-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'hablando / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_223_kevin simon mancera 2.jpg" />\r\n</div>\r\n</div>\r\n<p> hablando / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/223_KSMV.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fhablando-kevin-mancera%2F" frameborder="0" ></iframe>', '2017-9-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Entre Sombras / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_CCXXII_kevin_mancera_S.jpg" />\r\n</div>\r\n</div>\r\n<p> Entre Sombras / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/CCXXII_k.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fentre-sombras-kevin-mancera%2F" frameborder="0" ></iframe>', '2017-9-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Entre Sombras / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_CCXXII_kevin_mancera_S.jpg" />\r\n</div>\r\n</div>\r\n<p> Entre Sombras / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/CCXXII_k.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fentre-sombras-kevin-mancera%2F" frameborder="0" ></iframe>', '2017-9-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Trance / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_kevin_simon_mancera_CCXXI.jpg" />\r\n</div>\r\n</div>\r\n<p> Trance / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/kevin_simon_CCXXI.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Ftrance-kevin-mancera%2F" frameborder="0" ></iframe>', '2017-9-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Siempre he querido dibujar este paisaje / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/12_lluvia.gif" />\r\n</div>\r\n</div>\r\n<p> Siempre he querido dibujar este paisaje / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlistlluvia.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fsiempre-he-querido-dibujar-este-paisaje%2F" frameborder="0" ></iframe>', '2017-10-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Soft Winds / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_kevinsimon_CCXX.jpg" />\r\n</div>\r\n</div>\r\n<p> Soft Winds / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/kevinsimon_CCXX.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fsoft-winds-kevin-mancera%2F" frameborder="0" ></iframe>', '2017-10-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Aún Vivo / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_Kevin20.jpg" />\r\n</div>\r\n</div>\r\n<p> Aún Vivo / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/Kevin20.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fa%C3%BAn-vivo-kevin-mancera%2F" frameborder="0" ></iframe>', '2017-10-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Es ahora / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/bus.gif" />\r\n</div>\r\n</div>\r\n<p> Es ahora / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist_es_ahora.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fes-ahora%2F" frameborder="0" ></iframe>', '2017-10-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Eu Tentei / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_kevin_simon_mancera_ CCXVIII.jpg" />\r\n</div>\r\n</div>\r\n<p> Eu Tentei / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XXXV.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxxxv-eu-tentei%2F" frameborder="0" ></iframe>', '2017-10-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'dies Solis / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XXXIV.jpg" />\r\n</div>\r\n</div>\r\n<p> dies Solis / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist_dies.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fdies-solis%2F" frameborder="0" ></iframe>', '2017-11-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, '69 / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_Kevin_Simon_Mancera_ CCXVII_JPG.jpg" />\r\n</div>\r\n</div>\r\n<p> 69 / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XXXIII.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxxxiii-69%2F" frameborder="0" ></iframe>', '2017-11-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'MPGA / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XXXII.jpg" />\r\n</div>\r\n</div>\r\n<p> MPGA / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist_pospun.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fmpga%2F" frameborder="0" ></iframe>', '2017-11-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCVI / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XXXI.jpg" />\r\n</div>\r\n</div>\r\n<p> CCVI / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XXXI.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxxxi%2F" frameborder="0" ></iframe>', '2017-11-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Palida luna / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XXIX.jpg" />\r\n</div>\r\n</div>\r\n<p> Palida luna / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XIX.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxix%2F" frameborder="0" ></iframe>', '2017-11-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Panzerotti / by sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XVIII.jpg" />\r\n</div>\r\n</div>\r\n<p> Panzerotti / by sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist_it.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fpanzerotti%2F" frameborder="0" ></iframe>', '2017-12-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCXIV / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_kevin_simon_mancera_ CCXIV.jpg" />\r\n</div>\r\n</div>\r\n<p> CCXIV / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XXVII.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxxvii%2F" frameborder="0" ></iframe>', '2017-12-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Dinosaurios / by Sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_dinos2.png" />\r\n</div>\r\n</div>\r\n<p> Dinosaurios / by Sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/13_playlist25.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fdinosaurios-sergio-mancera%2F" frameborder="0" ></iframe>', '2017-12-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Rock me baby / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_equivocado.jpg" />\r\n</div>\r\n</div>\r\n<p> Rock me baby / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/X25.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Frock-me-baby%2F" frameborder="0" ></iframe>', '2017-12-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Hola / by Sergio Mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_rsz_h665_1_161.gif" />\r\n</div>\r\n</div>\r\n<p> Hola / by Sergio Mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/13_playlist23.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fhola%2F" frameborder="0" ></iframe>', '2017-12-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCXII / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_midiendose.jpg" />\r\n</div>\r\n</div>\r\n<p> CCXII / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/pXXIII.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxxiii%2F" frameborder="0" ></iframe>', '2018-1-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Cha Cha / by Sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_robot2.jpg" />\r\n</div>\r\n</div>\r\n<p> Cha Cha / by Sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist21.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fcha-cha%2F" frameborder="0" ></iframe>', '2018-1-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'XX / Underground Roots / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XX.jpg" />\r\n</div>\r\n</div>\r\n<p> XX / Underground Roots / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XX.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxx%2F" frameborder="0" ></iframe>', '2018-1-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, '7090 / by Sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_rsz_h665_1_144.png" />\r\n</div>\r\n</div>\r\n<p> 7090 / by Sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist19.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2F7090-sergio-mancera%2F" frameborder="0" ></iframe>', '2018-1-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCX / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XVIII2.jpg" />\r\n</div>\r\n</div>\r\n<p> CCX / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XVIII.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxviii-ksm%2F" frameborder="0" ></iframe>', '2018-1-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'La ciudad sigue durmiendo / by Sergio Mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_13_seminario_v3.png" />\r\n</div>\r\n</div>\r\n<p> La ciudad sigue durmiendo / by Sergio Mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist17.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fla-ciudad-sigue-durmiendo%2F" frameborder="0" ></iframe>', '2018-2-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCIX / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_kevinsimonmancera13_XVI.jpg" />\r\n</div>\r\n</div>\r\n<p> CCIX / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XVI.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxvi%2F" frameborder="0" ></iframe>', '2018-2-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Estamos flotando / by Sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_flotando.png" />\r\n</div>\r\n</div>\r\n<p> Estamos flotando / by Sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist15.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Festamos-flotando%2F" frameborder="0" ></iframe>', '2018-2-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Talking Drums / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XIV.jpg" />\r\n</div>\r\n</div>\r\n<p> Talking Drums / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XIV%20talking%20drums.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Ftalking-drums%2F" frameborder="0" ></iframe>', '2018-2-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Sagen ja, sagen nein / by Alejandra A. (Almeja)', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_XIII.jpg" />\r\n</div>\r\n</div>\r\n<p> Sagen ja, sagen nein / by Alejandra A. (Almeja) </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist13.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fsagen-ja-sagen-nein-mar%C3%ADa-alejandra-alarc%C3%B3n%2F" frameborder="0" ></iframe>', '2018-2-27', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCVII / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_onfire.jpg" />\r\n</div>\r\n</div>\r\n<p> CCVII / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XII.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxii%2F" frameborder="0" ></iframe>', '2018-3-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'me voy / by Sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_king.png" />\r\n</div>\r\n</div>\r\n<p> me voy / by Sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/12_playlist12.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fme-voy%2F" frameborder="0" ></iframe>', '2018-3-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCVI / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_imagen_11K" />\r\n</div>\r\n</div>\r\n<p> CCVI / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/XI.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&light=1&hide_artwork=1&feed=%2FLamalaestrella%2Fxi%2F" frameborder="0" ></iframe>', '2018-3-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Obligaciones / by Sergio mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_X.gif" />\r\n</div>\r\n</div>\r\n<p> Obligaciones / by Sergio mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist10.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fobligaciones%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-3-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'CCV / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_imagen 9K.jpg" />\r\n</div>\r\n</div>\r\n<p> CCV / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist9.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fix%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-3-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'De vuelta / by Sergio Mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_imagen 8S.jpg" />\r\n</div>\r\n</div>\r\n<p> De vuelta / by Sergio Mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist8.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fde-vuelta%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-4-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'El ocaso / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_imagen 7K.jpg" />\r\n</div>\r\n</div>\r\n<p> El ocaso / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist7.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fel-ocaso%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-4-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Yacer / by Sergio Mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/tercero.gif" />\r\n</div>\r\n</div>\r\n<p> Yacer / by Sergio Mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist6.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fyacer%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-4-15', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Bananas / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_13_lamala K4.jpg" />\r\n</div>\r\n</div>\r\n<p> Bananas / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist5.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fbananas%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-4-22', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'La ciudad duerme / by Sergio Mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_lamalaestrella S2.png" />\r\n</div>\r\n</div>\r\n<p> La ciudad duerme / by Sergio Mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist4.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fla-ciudad-duerme%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-4-29', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Low ways II / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_lamala K3.jpg" />\r\n</div>\r\n</div>\r\n<p> Low ways II / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist%203.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2F2-low-ways-ii%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-5-1', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'Low ways I / by K.S.M', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_lamala K1.jpg" />\r\n</div>\r\n</div>\r\n<p> Low ways I / by K.S.M </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist%20estrella%201.jpg" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2F1%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-5-8', 'Primero');

INSERT INTO `playlists` (`id`, `titulo`, `contenido`, `fecha`, `year`) 
VALUES (NULL, 'El fin / by  Sergio Mancera', '<div class="wrap">\r\n<div id="img_wrap">\r\n<img class="normal" src ="http://volcanmudo.com/lamalaestrella/files/gimgs/13_lamala S1.jpg" />\r\n</div>\r\n</div>\r\n<p> El fin / by  Sergio Mancera </p>\r\n<a href="http://volcanmudo.com/lamalaestrella/files/gimgs/playlist%202.png" target="_blank"><p><em>Playlist</em></p> </a>\r\n<iframe class="frame" width="78" height="60"  src="https://www.mixcloud.com/widget/iframe/?feed=https%3A%2F%2Fwww.mixcloud.com%2FLamalaestrella%2Fel-fin%2F&hide_cover=1&mini=1&hide_artwork=1&light=1" frameborder="0" ></iframe>', '2018-5-15', 'Primero');
